@HostAddress = http://localhost:5136

GET {{HostAddress}}/sets/
Accept: application/json

### Read a specific one
GET {{HostAddress}}/sets/6e215ad7-6987-4382-83c2-3327f1e35867
Accept: application/json

### Create a new set
POST {{HostAddress}}/sets
Content-Type: application/json

{
    "name": "Motos" 
}

### Update previously added set
PUT {{HostAddress}}/sets/569f6667-3ca4-4ac3-a405-7e8ab80c4c98
Content-Type: application/json

{
    "name": "Body shots" 
}

### Delete the record with a given ID
DELETE {{HostAddress}}/sets/1a278731-40ee-48bf-8260-f75f04ebfb36

### Get all flashcards
GET {{HostAddress}}/flashcards/

### Get a new flashcard from the set
GET {{HostAddress}}/sets/cba6ee84-f5ef-4174-9302-cfead34d4aa7/flashcards/

### Create a new flashcard
POST {{HostAddress}}/flashcards/
Content-Type: application/json

{
    "keyword": "huevo",
    "definition": "jajo" 
}

### Update one record
PUT {{HostAddress}}/flashcards/cba6ee84-f5ef-4174-9302-cfead34d4aa4
Content-Type: application/json

{
    "keyword": "gallina",
    "definition": "chicken"
}

### Delete the record with a given ID
DELETE {{HostAddress}}/flashcards/fa3f3fb8-4b75-4829-a018-b5a78e14d6c9