@HostAddress = http://localhost:5136

GET {{HostAddress}}/sets/
Accept: application/json

### Read a specific one
GET {{HostAddress}}/sets/cba6ee84-f5ef-4174-9302-cfead34d4aa7
Accept: application/json

### Create a new set
POST {{HostAddress}}/sets
Content-Type: application/json

{
    "name": "Motos" 
}

### Update previously added set
PUT {{HostAddress}}/sets/569f6667-3ca4-4ac3-a405-7e8ab80c4c98
Content-Type: application/json

{
    "name": "Body shots" 
}

### Delete the record with a given ID
DELETE {{HostAddress}}/sets/1a278731-40ee-48bf-8260-f75f04ebfb36

### Get all flashcards
GET {{HostAddress}}/flashcards/

### Get a new flashcard from the set
GET {{HostAddress}}/sets/cba6ee84-f5ef-4174-9302-cfead34d4aa7/flashcards/

### Create a new flashcard without a set
POST {{HostAddress}}/flashcards/
Content-Type: application/json

{
    "keyword": "huevo",
    "definition": "jajo" 
}

### Create a new flashcard to the set
POST {{HostAddress}}/sets/cba6ee84-f5ef-4174-9302-cfead34d4aa7/flashcards/
Content-Type: application/json

{
    "keyword": "zapatos",
    "definition": "buciory"
}

### Update one record
PUT {{HostAddress}}/flashcards/2b7d54d8-abe2-41dd-9a52-b638902768b5
Content-Type: application/json

{
    "keyword": "zapatitoos",
    "definition": "buciki"
}

### Delete the record with a given ID
DELETE {{HostAddress}}/flashcards/2b7d54d8-abe2-41dd-9a52-b638902768b5